version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Pythonのバージョンを指定
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # 依存関係をインストール
  pre_build:
    commands:
      - echo Running connectivity tests...
  build:
    commands:
      - start_time=$(date +%s)  # テスト開始時間を記録
      - python -m unittest discover tests/  # テストを実行
      - end_time=$(date +%s)  # テスト終了時間を記録
      - duration=$((end_time - start_time))  # 実行時間を計算
      - echo "Test execution time: $duration seconds" > test_duration.txt  # 実行時間をファイルに保存
      - echo Uploading duration to S3...
      - aws s3 cp test_duration.txt s3://cicd-kiki-bucket/test_duration.txt  # S3にアップ
  post_build:
    commands:
      - echo Tests completed
