version: 0.2

phases:
  install:
    commands:
      - echo Testing internet connection...
      - curl -I https://www.google.com  # Googleに接続を試みる
  build:
    commands:
      - echo Internet connection test completed.
