version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - yum install -y chromium-chromedriver  # Amazon Linuxの場合のインストール
      - export PATH=$PATH:/usr/lib/chromium-browser  # 必要に応じてパスを追加
  pre_build:
    commands:
      - echo Running tests...
      - python selenium_test.py  # Seleniumテストスクリプトの実行
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo Uploading screenshot to S3...
      - aws s3 cp search_results.png s3://your-s3-bucket-name/
artifacts:
  files:
    - '**/*'
  base-directory: build
