version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y epel-release  # EPELリポジトリを追加
      - yum install -y wget unzip  # wgetとunzipをインストール
      - yum install -y chromium  # Chromiumをインストール
      - yum install -y chromium-chromedriver  # ChromeDriverをインストール
      - pip install -r requirements.txt  # Pythonの依存関係をインストール
  pre_build:
    commands:
      - echo Running tests...
      - python selenium_test.py  # Seleniumテストスクリプトの実行
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo Uploading screenshot to S3...
      - aws s3 cp search_results.png s3://your-s3-bucket-name/
artifacts:
  files:
    - '**/*'
  base-directory: build
