version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Pythonのバージョンを指定
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # 依存関係をインストール
  pre_build:
    commands:
      - echo Running connectivity tests...
  build:
    commands:
      - python tests/test_ping.py  # テストを直接実行
      - echo Uploading duration to S3...
      - aws s3 cp test_duration.txt https://cicd-kiki-bucket.s3.ap-northeast-1.amazonaws.com/test_duration.txt  # S3にアップロード
  post_build:
    commands:
      - echo Tests completed
