version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - yum install -y wget unzip  # wgetとunzipをインストール
      - echo Downloading ChromeDriver...
      - wget https://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip  # ChromeDriverをダウンロード
      - unzip chromedriver_linux64.zip -d /usr/local/bin/  # ChromeDriverを解凍
      - chmod +x /usr/local/bin/chromedriver  # 実行権限を追加
      - echo Downloading Chromium...
      - wget https://download-chromium.appspot.com/dl/Linux_x64?type=snapshots -O chromium.zip  # Chromiumをダウンロード
      - unzip chromium.zip -d /usr/local/bin/chrome-linux  # 解凍先を指定
      - ls /usr/local/bin/chrome-linux/chrome-linux  # 解凍したファイルを確認
      - chmod +x /usr/local/bin/chrome-linux/chrome-linux/<correct_executable>  # 正しいバイナリに実行権限を追加
      - pip install -r requirements.txt  # Pythonの依存関係をインストール
  pre_build:
    commands:
      - echo Running tests...
      - python selenium_test.py  # Seleniumテストスクリプトの実行
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
      - echo Uploading screenshot to S3...
      - aws s3 cp search_results.png s3://your-s3-bucket-name/
artifacts:
  files:
    - '**/*'
  base-directory: build
